name: Update ReadMe & SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependancies
        run: npm install

      - name: Install OpenAPI Generator
        run: |
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli version

      - name: Checkout php SDK repository
        uses: actions/checkout@v4
        with:
          repository: HelloAsso/helloasso-php
          path: helloasso-php
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate php SDK
        run: |
          openapi-generator-cli generate -i helloasso.json -g php -o helloasso-php

      - name: Commit and push changes if needed for php
        run: |
          cd helloasso-php
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit for php"
          else
            git commit -m "Update php SDK from OpenAPI Generator"
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HelloAsso/helloasso-php.git main
          fi

        - name: Checkout node SDK repository
          uses: actions/checkout@v4
          with:
            repository: HelloAsso/helloasso-node
            path: helloasso-node
            token: ${{ secrets.GH_TOKEN }}
  
        - name: Generate node SDK
          run: |
            openapi-generator-cli generate -i helloasso.json -g javascript -o helloasso-node

        - name: Commit and push changes if needed for node
          run: |
            cd helloasso-node
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            if git diff --cached --quiet; then
              echo "No changes to commit for node"
            else
              git commit -m "Update node SDK from OpenAPI Generator"
              git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HelloAsso/helloasso-node.git main
            fi

        - name: Checkout python SDK repository
          uses: actions/checkout@v4
          with:
            repository: HelloAsso/helloasso-python
            path: helloasso-python
            token: ${{ secrets.GH_TOKEN }}
  
        - name: Generate python SDK
          run: |
            openapi-generator-cli generate -i helloasso.json -g python -o helloasso-python --additional-properties=packageName=helloasso-python
  
        - name: Commit and push changes if needed for python
          run: |
            cd helloasso-python
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            if git diff --cached --quiet; then
              echo "No changes to commit for python"
            else
              git commit -m "Update python SDK from OpenAPI Generator"
              git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HelloAsso/helloasso-python.git main
            fi

      - name: Update ReadMe
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
          API_ID: ${{ secrets.API_ID }}
        run: node index.js