name: Update ReadMe & SDK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependancies
        run: npm install

      - name: Install OpenAPI Generator
        run: |
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli version

      - name: Checkout php SDK repository
        uses: actions/checkout@v4
        with:
          repository: HelloAsso/helloasso-php
          path: helloasso-php
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Generate php SDK
        run: |
          openapi-generator-cli generate -i helloasso.json -g php -o helloasso-php

      - name: Commit, tag and push changes if needed for php
        run: |
          cd helloasso-php
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit for php"
          else
            git commit -m "Update php SDK from OpenAPI Generator"
            CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
            MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
            MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
            PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
            git tag $NEW_VERSION
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HelloAsso/helloasso-php.git main --tags
          fi

      - name: Checkout node SDK repository
        uses: actions/checkout@v4
        with:
          repository: HelloAsso/helloasso-node
          path: helloasso-node
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
  
      - name: Generate node SDK
        run: |
          openapi-generator-cli generate -i helloasso.json -g javascript -o helloasso-node

      - name: Commit, tag and push changes if needed for node
        run: |
          cd helloasso-node
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit for node"
          else
            git commit -m "Update node SDK from OpenAPI Generator"
            CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
            MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
            MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
            PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
            sed -i "s/\"version\": \".*\"/\"version\": \"${NEW_VERSION}\"/" package.json
            git add package.json
            git commit --amend --no-edit
            git tag $NEW_VERSION
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HelloAsso/helloasso-node.git main --tags
          fi

      - name: Checkout python SDK repository
        uses: actions/checkout@v4
        with:
          repository: HelloAsso/helloasso-python
          path: helloasso-python
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
  
      - name: Generate python SDK
        run: |
          openapi-generator-cli generate -i helloasso.json -g python -o helloasso-python --additional-properties=packageName=helloasso_python
  
      - name: Commit, tag and push changes if needed for python
        run: |
          cd helloasso-python
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit for python"
          else
            git commit -m "Update python SDK from OpenAPI Generator"
            CURRENT_VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
            MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
            MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)
            PATCH=$(echo $CURRENT_VERSION | cut -d. -f3)
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="${MAJOR}.${MINOR}.${NEW_PATCH}"
            sed -i "s/VERSION = \".*\"/VERSION = \"${NEW_VERSION}\"/" setup.py
            git add setup.py
            git commit --amend --no-edit
            git tag $NEW_VERSION
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/HelloAsso/helloasso-python.git main --tags
          fi

      - name: Update ReadMe
        env:
          README_API_KEY: ${{ secrets.README_API_KEY }}
          API_ID: ${{ secrets.API_ID }}
        run: node index.js